name: Deploy Application

on:
  push:
    tags:
      - 'v*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get version from tag
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: Deploy to production
        uses: bjarneo/copepod/.github/actions/copepod/action.yml@main
        with:
          host: 65.108.80.226
          user: root
          ssh_key: ${{ secrets.SSH_KEY }}
          image: remix-demo
          tag: ${{ steps.get_version.outputs.VERSION }}
          container_name: remix-demo
          container_port: 3000
          host_port: 300